secret = [10, 45, 10, 9, 115, 101, 99, 114, 101, 116, 107, 101, 121, 18, 32, 84, 150, 201, 178, 27, 121, 168, 24, 51, 97, 96, 22, 135, 128, 71, 191, 130, 138, 251, 85, 120, 137, 175, 184, 61, 253, 154, 101, 74, 244, 102, 164, 10, 55, 10, 3, 113, 48, 49, 18, 48, 36, 235, 125, 211, 126, 20, 73, 236, 244, 23, 108, 211, 180, 121, 61, 27, 39, 153, 139, 34, 130, 87, 254, 94, 129, 87, 35, 27, 143, 218, 171, 66, 50, 227, 61, 222, 6, 168, 62, 199, 85, 0, 29, 112, 187, 222, 250, 147, 10, 55, 10, 3, 116, 48, 49, 18, 48, 36, 235, 125, 211, 126, 20, 73, 236, 244, 23, 108, 211, 180, 121, 61, 27, 39, 153, 139, 34, 130, 87, 254, 94, 129, 87, 35, 27, 143, 218, 171, 66, 50, 227, 61, 222, 6, 168, 62, 199, 85, 0, 29, 112, 187, 222, 250, 147]

[[metrics]]
  Help = "Hana - allocated rowstore size"
  MetricType = "gauge"
  Name = "hdb_allocated_rowstore_size1"
  SQL = "select allocated_size,port from <SCHEMA>.m_rs_memory where category='TABLE'"
  SchemaFilter = ["sys"]
  TagFilter = []

[[metrics]]
  Help = "Active Hana connections per service"
  MetricType = "gauge"
  Name = "hdb_active_connections1"
  SQL = "select COUNT(IFNULL(C.CONNECTION_STATUS, 'IDLE')) as connections, S.service_name as service FROM <SCHEMA>.M_CONNECTIONS C inner join <SCHEMA>.M_SERVICES S on C.PORT = S.PORT WHERE C.LOGICAL_CONNECTION_ID = C.CONNECTION_ID AND C.OWN = 'FALSE' group by S.service_name"
  SchemaFilter = ["sys"]
  TagFilter = []

[[metrics]]
  Help = "Check if hana db tenant is active"
  MetricType = "gauge"
  Name = "hdb_active_status1"
  SQL = "select top 1 (case when active_status = 'YES' then 1 else -1 end), database_name from <SCHEMA>.m_databases"
  SchemaFilter = ["sys"]
  TagFilter = []

[[tenants]]
  ConnStr = "sapseqh.lenze.com:32041"
  Name = "Q01"
  Tags = ["erp"]
  User = "hanaremote"

[[tenants]]
  ConnStr = "sapt01h.lenze.com:31041"
  Name = "t01"
  Tags = ["abap", "erp"]
  User = "hanaremote"
